/**
 * The report, rendered from a real fixture.
 *
 * Not a route users reach. It exists so the report can be looked at without an
 * account, a Gemini key or a thirty-second wait — and so a token or layout
 * change can be checked against the whole page rather than against a component
 * in isolation.
 *
 * The fixture in `lib/fixtures/report.json` is **generated by the real
 * pipeline**, not written by hand: parsing, matching, the ATS rules, the scoring
 * engine and the grounding validator all ran to produce it. Only the model's
 * answers were scripted. That matters — a hand-written fixture is a record of
 * what I assumed the API emits, and this is a record of what it actually emits.
 *
 * One consequence worth knowing: the fixture has no bullet suggestions. The
 * scripted resume content did not survive span verification against the real
 * PDF, so those bullets were dropped exactly as they would be in production.
 * The suggestion component is exercised on `/design` instead.
 */
import { AtsChecklist, BulletSuggestions, Recommendations } from "@/components/report/Advice";
import { ScoreBreakdown } from "@/components/report/ScoreBreakdown";
import { SkillLedger } from "@/components/report/SkillLedger";
import { ThreadMap, type ThreadRow } from "@/components/report/Thread";
import { Verdict } from "@/components/report/Verdict";
import { Label } from "@/components/ui/Panel";
import { ToastProvider } from "@/components/ui/Toast";
import fixture from "@/lib/fixtures/report.json";
import type { AnalysisReport } from "@/lib/types";

const report = fixture as unknown as AnalysisReport;

export default function ReportPreviewPage() {
  const requirements = report.job.requirements ?? [];
  const matches = report.matches.matches ?? [];

  const byId = new Map(matches.map((match) => [match.requirement_id, match]));
  const rows: ThreadRow[] = requirements
    .map((requirement): ThreadRow => {
      const match = byId.get(requirement.id ?? "");
      const strength = match?.strength ?? 0;
      const best = match?.evidence?.[0];
      return {
        id: requirement.id ?? requirement.text,
        requirement: requirement.text,
        priority: requirement.priority,
        state:
          !match || match.status === "missing" || strength === 0
            ? "absent"
            : match.status === "partial" || strength <= 0.5
              ? "listed"
              : "shown",
        evidence: best?.span.text,
        location: best ? "Experience" : undefined,
      };
    })
    .sort(
      (a, b) =>
        ({ must: 0, strong: 1, nice: 2 })[a.priority] -
          ({ must: 0, strong: 1, nice: 2 })[b.priority] ||
        ({ absent: 0, listed: 1, shown: 2 })[a.state] -
          ({ absent: 0, listed: 1, shown: 2 })[b.state],
    );

  return (
    <ToastProvider>
      <main className="mx-auto w-full max-w-[1100px] px-5 sm:px-8 py-10 sm:py-14 flex flex-col gap-14">
        <div className="flex flex-col gap-1 pb-2 border-b border-line-subtle">
          <Label>Development preview · generated by the real pipeline</Label>
        </div>

        <Verdict
          scores={report.scores}
          headline={report.headline}
          body={report.verdict}
          roleTitle="Backend Engineer at Northwind, entry"
          requirementCount={requirements.length}
          degradedStages={report.degraded_stages ?? []}
        />

        <ThreadMap rows={rows} />

        <Recommendations items={report.recommendations ?? []} />

        <BulletSuggestions suggestions={report.bullet_suggestions ?? []} />

        <SkillLedger requirements={requirements} matches={matches} />

        <AtsChecklist
          findings={report.ats.findings ?? []}
          checksRun={report.ats.checks_run}
          hiddenText={report.ats.hidden_text_detected}
        />

        <ScoreBreakdown scores={report.scores} />
      </main>
    </ToastProvider>
  );
}
