"""Roleva domain models — the contract every subsystem shares.

These schemas are the boundary between stages, between Python and TypeScript
(via generated OpenAPI types), and between the v1 analyzer and the future
resume builder. Change them deliberately.
"""

from roleva.models.ats import AtsFinding, AtsReport, AtsRuleId, AtsSeverity
from roleva.models.common import (
    ConfidenceBand,
    DateRange,
    Provenance,
    SourceDoc,
    Span,
    StrictModel,
    band_for,
)
from roleva.models.evidence import (
    ADJACENT_STRENGTH,
    ORIGIN_STRENGTH,
    Evidence,
    MatchReport,
    MatchStatus,
    RequirementMatch,
)
from roleva.models.job import (
    JD_SCHEMA_VERSION,
    PRIORITY_WEIGHT,
    JobTarget,
    Priority,
    Quantifier,
    Requirement,
    RequirementCategory,
    Seniority,
)
from roleva.models.report import (
    REPORT_SCHEMA_VERSION,
    AnalysisReport,
    AnalysisStatus,
    BulletSuggestion,
    ProgressEvent,
    Recommendation,
    SectionFeedback,
    Severity,
    Stage,
)
from roleva.models.resume import (
    RESUME_SCHEMA_VERSION,
    Bullet,
    ContactInfo,
    CredentialItem,
    DetectedSection,
    EducationItem,
    ExperienceItem,
    ProjectItem,
    ResumeDocument,
    SectionKind,
    SkillMention,
    SkillOrigin,
)
from roleva.models.scoring import (
    BAND_THRESHOLDS,
    Band,
    ExpectedBand,
    Percentile,
    Score,
    ScoreComponent,
    ScoreKind,
    ScoreReport,
    band_for_score,
)

__all__ = [
    "ADJACENT_STRENGTH",
    "BAND_THRESHOLDS",
    "JD_SCHEMA_VERSION",
    "ORIGIN_STRENGTH",
    "PRIORITY_WEIGHT",
    "REPORT_SCHEMA_VERSION",
    "RESUME_SCHEMA_VERSION",
    "AnalysisReport",
    "AnalysisStatus",
    "AtsFinding",
    "AtsReport",
    "AtsRuleId",
    "AtsSeverity",
    "Band",
    "Bullet",
    "BulletSuggestion",
    "ConfidenceBand",
    "ContactInfo",
    "CredentialItem",
    "DateRange",
    "DetectedSection",
    "EducationItem",
    "Evidence",
    "ExpectedBand",
    "ExperienceItem",
    "JobTarget",
    "MatchReport",
    "MatchStatus",
    "Percentile",
    "Priority",
    "ProgressEvent",
    "ProjectItem",
    "Provenance",
    "Quantifier",
    "Recommendation",
    "Requirement",
    "RequirementCategory",
    "RequirementMatch",
    "ResumeDocument",
    "Score",
    "ScoreComponent",
    "ScoreKind",
    "ScoreReport",
    "SectionFeedback",
    "SectionKind",
    "Seniority",
    "Severity",
    "SkillMention",
    "SkillOrigin",
    "SourceDoc",
    "Span",
    "Stage",
    "StrictModel",
    "band_for",
    "band_for_score",
]
